apiVersion: apps/v1
kind: Deployment
metadata:
  name: efs-provisioner
spec:
  selector:
    matchLabels:
      app: efs-provisioner
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: efs-provisioner
    spec:
      containers:
      - name: efs-provisioner
        image: quay.io/external_storage/efs-provisioner:v0.1.0
        env:
        - name: FILE_SYSTEM_ID
          value: fs-8737ccfc
        - name: AWS_REGION
          value: us-east-2
        - name: PROVISIONER_NAME
          value: satyam/aws-efs
        volumeMounts:
        - name: pv-volume
          mountPath: /persistentvolumes
      volumes:
      - name: pv-volume
        nfs:
          server: fs-8737ccfc.efs.us-east-2.amazonaws.com
          path: /    

