on:
  pull_request:
    paths:
    - app/**
  push:
    paths:
    - app/**
    branches:        
    - master         
    
    
    # set this to your preferred AWS region, e.g. us-west-1
env:      
  ECR_REPOSITORY: peach          # set this to your Amazon ECR repository name
  CONTAINER_NAME: MY_PEACH_APP

jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Login to ECR
      id: ecr
      uses: jwalton/gh-ecr-login@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-2
    - name: Build and tag the image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REPOSITORY ./app
    - name: Tag image
      run: |
        docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
        #    docker tag peach_ecr:latest 958056551390.dkr.ecr.us-east-2.amazonaws.com/peach_ecr:latest
    - name: Push
      if: github.ref == 'refs/heads/master'
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        #docker push 958056551390.dkr.ecr.us-east-2.amazonaws.com/peach_ecr:latest
