on:
  pull_request:
    paths:
    - app/**
    - manifests/**
  push:
    paths:
    - app/**
    - manifests/**
    branches:        
    - master         
    
    
env:      
#ECR_REPOSITORY: peach          # set this to your Amazon ECR repository name
  CONTAINER_IMAGE: peach
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-2
  EKS_CLUSTER_NAME: peach-eks

jobs:
  build-and-push:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Login to ECR
      id: ecr
      uses: jwalton/gh-ecr-login@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-2
    - name: Build and tag the image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
              docker build \
                -t $CONTAINER_IMAGE \
                -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE ./app
    - name: Push
      if: github.ref == 'refs/heads/master'
      run: |
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE
        #deploy:
        # runs-on: ubuntu-latest
        #needs: [build]


        #  steps:
  - name: Setup kubeconfig
    #id: setup-kubeconfig
    run: |
      aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME

      #  - uses: actions/checkout@v2
      #  - name: AWS Credentials
      #    uses: aws-actions/configure-aws-credentials@v1
      #    with:
      #      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #      aws-region: us-east-2  
   
  - name: Deploy k8s yaml
    uses: actions/checkout@v2
    env:
      K8S_YAML_DIR: ./manifests 
    run: |  
      cd $K8S_YAML_DIR
      curl -s -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
      chmod u+x ./kustomize
      kubectl apply -k $K8S_YAML_DIR/




